CREATE TABLE TEST_RUNS(
ID INT NOT NULL,
TEST_TYPE VARCHAR(20),
TEST_COMMAND VARCHAR(2000),
TEST_DATE DATE,
PRIMARY KEY (ID)
);

CREATE TABLE TEST_DETAIL(
ID INT NOT NULL,
TEST_ID INT NOT NULL REFERENCES TEST_RUNS(ID),
FILE_NAME VARCHAR(2000),
FILE_CONTENT VARCHAR(10000),
PRIMARY KEY (ID)
);

